---

- name: installing-jenkins
  hosts: all
  become: true
  tasks:
    - name: system-update
      apt:
        update_cache: yes
    - name: getting-jenkins-link
      become: true
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]  https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: system-update
      apt:
        update-cache: yes

        
    - name: install-java
      apt:
        name: openjdk-17-jre
        state: present

    - name: install-jenkins
      apt:
        name: jenkins
        state: present

    - name: start-jenkins
      service:
        name: jenkins
        state: started

